### ISSUE TITLE
File Upload Service

### ISSUE THREAD

**Issue by Kodemon** [reach/api#7]
Need to add a robust file uploader service

**Comment by mattgi** [comment]
I would nearly force `S3` upon consumers for beta.. but perhaps `local` is helpful for dev.

I think a generic Media model would be helpful within the module.. that supports a local or S3 URI for the location of the media file. The Media model then has like a `media_type`, `mime_type` and `storage_type`..

e.g.
```
{ "mediaType":  "image",  "mimeType": "image/jpeg", "storageType": "s3", "uri": "media/c2aba810e5ad11e4b22f07cfa304866a/original.jpeg" }
{ "mediaType":  "video",  "mimeType": "video/mp4", "storageType": "local", "uri": "temp/media/c2aba810e5ad11e4b22f07cfa304866a/video.mp4" }
```
in the future:
```
{ "mediaType":  "video",  "mimeType": "video/mp4", "storageType": "youtube", "uri": "//youtu.be/scY5vcCpqZ8" }
```

Quite separate to 'file upload' but I believe it all lives within one module as the controller actions need to be dealing with CRUD and its different for each storage type. For example Create for S3 would be more about returning a temp. access policy that can be used to push from client to S3 and then a Update to store the resulting URI against the created model or something... 

Another approach, i guess, would be to have a different module for each storage type.. but I do think the flexibility and abstraction from the consumer and the storage is good.. as in, I dont care where u pull it from, but I need the media for Id 123... the module then goes, well based on this media model, the storage type is S3.. and based on the config.. your bucket is XYZ, so I can retrieve it for you.. etc.

**Comment by Kodemon** [comment]
I think your second approach is what I am thinking, module with file routes and abstract service in the back end that the API developer worries about. Client's shouldn't care much, and if they do they can just inform them where they want their files stored.

**Comment by mattgi** [comment]
there is a difference in the way a file uploaded though.. in that, if its S3, the typical flow is:
-> request token from API
-> use token to upload file directly to S3 (client side only)
-> create a Media/File model and include the S3 response uri in the model for it to be persisted in the API.

if its local storage, the flow is more like
-> upload file, which in turn, creates a model and saves it

So 2 requests to API + 1 request to S3.. versus 1 request to API..

How do you envisage the routes looking to support both via the same routes? May be doable, just cant picture it myself yet.

**Comment by Kodemon** [comment]
Now support file uploads for local and S3

**Comment by Kodemon** [comment]
@mattgi as discussed we will be doing a temp storage of all uploaded files and put the additional uploads to 3rd party services as a queue.

Idea is to serve temp files until it has successfully uploaded to 3rd party service.
